name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:     
  docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha

  # deploy:
  #   needs:
  #     - docker
  #   runs-on: ubuntu-latest
  #   environment: kubernetes
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Branch deploy info
  #       if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'preview') }}
  #       run: echo "ArgoCD will try to update this deployment shortly."

  #     - name: Checkout
  #       if: ${{ github.event_name != 'pull_request' }}
  #       uses: actions/checkout@v4
        
  #     - name: Deploy using Argo CD
  #       if: ${{ github.event_name != 'pull_request' }}
  #       run: |
  #         # Access the commit SHA from GitHub context
  #         COMMIT_SHA="${{ github.sha }}"
          
  #         # Trim the first few characters to match the desired format (e.g., sha-c27d339)
  #         SHORT_SHA="sha-${COMMIT_SHA:0:7}"
          
  #         # Change image.tag in charts/drinkn/values.yaml
  #         sed -i "s|tag:.*|tag: \"$SHORT_SHA\"|" charts/drinkn/values.yaml

  #         # Commit and push the changes to the deploy branch
  #         git config --global user.name "github-actions[bot]"
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git add charts/drinkn/values.yaml
  #         git commit -m "Update image.tag to $SHORT_SHA"
  #         git push origin main